### PR TITLE
✨ Release 0.0.7 `daita-python-library`

### LINKED ISSUE #4: Show progress bar for uploads
Currently, the user does not get any information about the current state of the upload. We should implement a progress bar as terminal output to keep the user up-to-date.

### LINKED ISSUE #5: Remove `.env.development` file
Currently we do not gitignore the [.env.development](https://github.com/daita-technologies/daita-python-library/blob/main/daita/.env.development) file. While there is no security-critical information to date in there, we should move to gitignore this file and instead put the environment variable values as GitHub repository secrets. This would also imply, adjusting slightly the current build process in the way that the GitHub Actions load the secrets correctly.

### PR DESCRIPTION
**Pull request by BEdaita**
### Product Roadmap

- [x] Resolves https://github.com/daita-technologies/roadmap/issues/23.

### Issues

- Fixes #5. ([#8](https://github.com/daita-technologies/daita-python-library/pull/8))
- Adds a partial solution for #6. ([#10](https://github.com/daita-technologies/daita-python-library/pull/10))
- Added #4. ([#11](https://github.com/daita-technologies/daita-python-library/pull/11))

image

### CODE REVIEW

**Comment by pcaversaccio** [comment]
@BEdaita I made a couple of changes:

- I added the full `CHANGELOG` in this PR description
- I removed all variables and imports that are not accessed.
- Why did you put `urllib3` as a dependency in the `setup.py`? I don't think it's required and I removed it.
- Fixed the formatting and some wording.
- Why is `tqdm` not used for the upload of ZIP?

**Comment by BEdaita** [comment]
- I don't use the `tqdm` for upload of zip. Because the dashboard of download zip task on front end is not support to display the current file is compress so I will display the status to sync the front end.
-  I set `urllib3` in the `setup.py` because on the library `requests` has a problem .You can check this [link](https://stackoverflow.com/questions/65886026/tls-ssl-connection-has-been-closed-eof)

**Review by pcaversaccio — COMMENTED** [review]
@BEdaita I made a couple of changes:

- I added the full `CHANGELOG` in this PR description.
- I removed all variables and imports that are not accessed.
- Why did you put `urllib3` as a dependency in the `setup.py`? I don't think it's required and I removed it.
- Fixed the formatting and some wording.
- Why is `tqdm` not used for the upload of ZIP?

**Comment by pcaversaccio** [comment]
can we use version `urllib3 1.26.12`? If yes, I will but `"urllib3>=1.26.2"`.

**Comment by BEdaita** [comment]
The reason why I set this version because I tested it. I am not sure the library works well. In the future, I will use another solution to upload not using HTTP protocol. In this version, It just makes sure the library work stable, I use retry to avoid crashing when use HTTP protocol

**Review by pcaversaccio — DISMISSED** [review]

**Comment by pcaversaccio** [comment]
ok I re-added everything - please check & validate my recent commits as well. If you agree, you can merge it. I will later make the release.

**Comment by pcaversaccio** [comment]
Made some final adjustments - please @BEdaita make a final test and merge thereafter. thx.

**Comment by pcaversaccio** [comment]
@BEdaita any update?

**Comment by BEdaita** [comment]
No problem, You can merge it , I will merge it.

**Pull request merged**
